/** Legacy variant ids for RemiMouse clip resolution (sprite era). */
export type AsciiMouseVariant =
  | 'micro'
  | 'caret'
  | 'thinking'
  | 'peek'
  | 'logoCompact'
  | 'logoHero'
  | 'agent'
  | 'skills'
  | 'prompts'
  | 'memories'
  | 'bookmarks'
  | 'parameters'
  | 'newChat'
  | 'hidePanel'
  | 'sidebarToggle'
  | 'warning'
  | 'attach'
  | 'mcp'
  | 'ai'
  | 'menu'
  | 'preset'
  | 'bookmark'
  | 'model'
  | 'tempChat';
